[tool.poetry]
name = "lextract"
version = "0.0.1"
description = ""
authors = ["Frankie Robertson <frankie@robertson.name>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.7"
click = ">=6.7"
plumbum = "^1.6.6"
pyahocorasick = { git = "https://github.com/frankier/pyahocorasick.git", branch = "stiff-2018-09-20-3" }
opencc = "^0.2"
finntk = ">=0.0.44"
conllu = "^1.1"
hfst = {version = "3.15.0.0b0",allows-prereleases = true}
wikiparse = {git = "https://github.com/frankier/wikiparse.git", commit = "d61cfff97625ef26cbb76f070e179f2e646ccc4c"}

[tool.poetry.dev-dependencies]
flake8 = "^3.5.0"
pre-commit = "^1.10.2"
pytest = "^4.1.1"
mypy = "0.650"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
